server:
  port: 10001
  tomcat:
    accept-count: 10000
    max-connections: 1000
    max-threads: 500

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    useHeadlessService: false
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    cache-refresh-executor-thread-pool-size: 10

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
logging:
  file: service-out.log
  level:
    org.bqf: DEBUG
    org.springframework: WARN
    
fallback: 
  useFallbackConfig: true
    
    